Tour/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Slider(models.Model):
    image = models.ImageField(upload_to='slider',
                              help_text='1920*1280 px')
    heading = models.CharField(max_length=255, null=True, blank=True)
    sub_heading = models.TextField(null=True, blank=True)
    link = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name = 'Slider'
        verbose_name_plural = 'Slider'


class AboutUs(models.Model):
    heading = models.CharField(max_length=255)
    description = RichTextField()

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name = 'About Us'
        verbose_name_plural = 'About Us'


class WhyUs(models.Model):
    heading = models.CharField(max_length=255)
    description = RichTextField()

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name = 'Why Us'
        verbose_name_plural = 'Why Us'


class OurStory(models.Model):
    heading = models.CharField(max_length=255)
    description = RichTextField()

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name = 'Story & Award'
        verbose_name_plural = 'Story & Awards'


class AwardImages(models.Model):
    ourstory = models.ForeignKey(OurStory, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to='awards', null=True, blank=True)
    url = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        verbose_name = "Award"
        verbose_name_plural = "Award"


class Destination(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)
    featured_image = models.ImageField(upload_to='destination',
                                       help_text='1920*1280 px')
    description = RichTextField()
    ordering = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Destination'
        verbose_name_plural = 'Destination'


class CompanyInfo(models.Model):
    favicon = models.ImageField(
        upload_to='images', default='', blank=True, null=True)
    logo = models.ImageField(
        upload_to='images', default='', blank=True, null=True)
    phone = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    secondary_email = models.EmailField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=100)

    short_description = models.TextField(max_length=255, blank=True, null=True)
    location_map = models.TextField(null=True, blank=True)
    video_url = models.CharField(max_length=255, null=True, blank=True)
    footer_text_copyright = models.CharField(
        max_length=100, null=True, blank=True)
    footer_copyright_url = models.URLField(
        default='', null=True, blank=True)
    facebook_link = models.URLField(null=True, blank=True)
    twitter_link = models.URLField(null=True, blank=True)
    youtube_link = models.URLField(null=True, blank=True)
    instagram_link = models.URLField(null=True, blank=True)
    linkedin_link = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    meta_title = models.CharField(
        max_length=255, default='', null=True, blank=True)
    meta_keyword = models.TextField(null=True, blank=True)
    meta_description = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'General Settings'
        verbose_name_plural = 'General Settings'


class Tour_Type(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    icon = models.ImageField(upload_to='tour_type')
    image = models.ImageField(upload_to='tour_type')
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    description = RichTextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tour Category'
        verbose_name_plural = 'Tour Category'


# class Includes(models.Model):
#     title = models.CharField(max_length=255)

#     def __str__(self):
#         return self.title

#     class Meta:
#         verbose_name = 'Includes'
#         verbose_name_plural = 'Includes'


# class Excludes(models.Model):
#     title = models.CharField(max_length=255)

#     def __str__(self):
#         return self.title

#     class Meta:
#         verbose_name = 'Excludes'
#         verbose_name_plural = 'Excludes'


class Tour(models.Model):
    DIFFICULTY_CHOICES = (
        ('Low', 'Low'),
        ('Moderate', 'Moderate'),
        ('High', 'High')
    )
    PUBLISH_CHOICES = (
        ('Enable', 'Enable'),
        ('Disable', 'Disable'),
    )
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    publish = models.CharField(
        choices=PUBLISH_CHOICES, default=1, max_length=15, null=True, blank=True)
    featured_image = models.ImageField(upload_to='tour')
    route_map = models.ImageField(upload_to='tour')
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    activity = models.ForeignKey(
        Tour_Type, on_delete=models.CASCADE)
    duration = models.IntegerField(null=True, blank=True)
    difficulty = models.CharField(
        choices=DIFFICULTY_CHOICES, max_length=50, default='Low', null=True, blank=True)
    max_altitude = models.CharField(max_length=100, null=True, blank=True)
    trip_start = models.CharField(
        max_length=100, default='Kathmandu', null=True, blank=True)
    trip_end = models.CharField(
        max_length=100, default='Kathmandu', null=True, blank=True)
    group_size = models.CharField(max_length=100, null=True, blank=True)
    meals = models.TextField(null=True, blank=True)
    accomodation = models.TextField(null=True, blank=True)
    regular_price = models.IntegerField(null=True, blank=True)
    sell_price = models.IntegerField(null=True, blank=True)
    overview = RichTextField()
    includes = RichTextField(null=True, blank=True)
    excludes = RichTextField(null=True, blank=True)
    additional_information = RichTextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Tour'
        verbose_name_plural = 'Tour'


class Gallery(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='tour/gallery', null=True, blank=True)

    class Meta:
        verbose_name = "Gallery"
        verbose_name_plural = "Gallery"


class Itinerary(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    day = models.IntegerField(null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Faq(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    question = models.CharField(max_length=255, null=True, blank=True)
    answer = models.TextField(null=True, blank=True)


class Blog(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    featured_image = models.ImageField(upload_to='blog')
    description = RichTextField()
    readtime = models.CharField(
        max_length=10, help_text='eg: 5 min', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blog'


class TeamCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Team Category'
        verbose_name_plural = 'Team Category'


class Team(models.Model):
    image = models.ImageField(upload_to='team', blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    designation = models.CharField(max_length=255, blank=True, null=True)
    description = RichTextField(blank=True, null=True)
    category = models.ForeignKey(TeamCategory, on_delete=models.CASCADE)
    order = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Team'
        verbose_name_plural = 'Team'


class FooterUseFulInfo(models.Model):
    companyinfo = models.ForeignKey(CompanyInfo, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=True)
    url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Useful Info'
        verbose_name_plural = 'Useful Info'


class Inquiry(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

templates/activities.html
{% extends "base.html" %}


{% block content %}
<div class="page-banner">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner-bredcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        <h1>Activities</h1>
        <ul class="breadcrumb">
          <li><a href="/">Home</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="adventure">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12 nepal-content">
        <h2>{{ single_act.name }}</h2>
        <p>{{ single_act.description | safe }}</p>
      </div>
      <div class="col-12 col-sm-12">
        <h4>Explore the Trips - {{single_act.name}}</h4>
      </div>
      {% if tours %}
        {% for i in tours %}
        <div class="col-12 col-sm-12 col-md-6 col-lg-4">
          <div class="adventure-box">
            <div class="box">
              <div class="imgBox">
                <img src="{{ i.featured_image.url }}" loading="lazy" alt="">
              </div>
              <div class="content">
                <a href="{% url 'tour-detail' i.slug %}" class="btn btn-book">Learn More</a>
                
              </div>
            </div>
            <h6 class="group"><i class="fa fa-trek"></i> {{i.activity}}</h6>
            {% comment %} <p class="reviews"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> of 31 reviews</p> {% endcomment %}
            <div class="price-box">
            {% if regular_price %}
              <span class="trip-card__regular-price">from <del>US$ {{i.regular_price}}</del></span>
              {% endif %}
              <span class="trip-card__sale-price">US$ <strong>{{ i.sell_price }}</strong><sup></sup></span>
            </div>
            <h5><a href="{% url 'tour-detail' i.slug %}">{{i.name}}</a></h5>
            <ul>
              <li><i class="fas fa-tachometer-alt"></i><span>Grade</span> <h6>{{i.difficulty }}</h6></li>
              <li><i class="far fa-calendar-alt"></i><span>Duration</span> <h6>{{i.duration}} Days</h6></li>
              <li><i class="fas fa-hiking"></i><span>Activity</span> <h6>{{i.activity}}</h6></li>
            </ul>
          </div>
        </div>
        {% endfor %}
      {% else %}
      <div class="col-12 col-sm-12">
        <h5>No result found...</h5>
      </div>
      {% endif %}
      {% comment %} <div class="col-12 col-sm-12">
        <ul class="pagination">
          <li class="page-item"><a class="page-link" href="#">Previous</a></li>
          <li class="page-item active"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
      </div> {% endcomment %}
    </div>
  </div>
</div>
{% endblock content %}

templates/blog-detail.html
{% extends "base.html" %}

{% block content %}


<div class="page-banner">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner-bredcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        {% comment %} <h1>Blog Details</h1> {% endcomment %}
        <ul class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li>Blog Details</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="blogdetail-body">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        <h2>{{single_blog.title}}</h2>
      </div>
      <div class="col-12 col-sm-12 col-md-8 col-lg-9">
        <h6>{{single_blog.created_at | date }}</h6>
        <p>{{ single_blog.description | safe }}</p>
        <div class="row blogpost">
          <div class="col-12 col-sm-12">
            <h4>Our Recent Blog</h4>
          </div>
          {% for recent_blog in recent_blogs %}
          <div class="col-12 col-sm-12 col-md-4 col-lg-4">
            <a href="{% url 'blog-detail' recent_blog.slug %}"><img src="{{ recent_blog.featured_image.url }}" loading="lazy" alt=""></a>
            <div class="blog-box">
              <h6>{{ recent_blog.created_at | date }}</h6>
              <h5><a href="{% url 'blog-detail' recent_blog.slug %}">{{ recent_blog.title }}</a></h5>
              <p>{{ recent_blog.description | safe | truncatechars:40}}</p>
              <a href="{% url 'blog-detail' recent_blog.slug %}" class="btn btn-continue">Continue Reading</a>
            </div>
          </div>
          {% endfor %}
         
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-4 col-lg-3">
        <div class="search-box1">
          <form id="custom-search-form" class="form-search form-horizontal pull-right">
            <div class="input-append span12">
              <div class="form-group has-search">
                <span class="fa fa-eye form-control-feedback"></span>
                <input type="text" class="form-control" placeholder="Search">
              </div>
            </div>
          </form>
        </div>
        <div class="catbox">
        
        <div class="relatepack">
          <h4>Featured Packages</h4>
          <ul>
          {% for i in featured_packages %}
            <li><a href="{% url 'tour-detail' i.slug %}"><img src="{{ i.featured_image.url }}" loading="lazy" alt=""> <h5>{{ i.name }}</h5></a></li>
            
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/booking-form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="page-banner">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12">
                    
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner-bredcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        <h1>Payment</h1>
        <ul class="breadcrumb">
          <li><a href="index.html">Home</a></li>
          <li>Payment</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="online-body">
  <div class="container">
    <div class="row tripdetails">
      <div class="col-12 col-sm-12 col-md-6 col-lg-6 tripdetail1">
        <span>1</span>
        <h5>Trip Details</h5>
        <p><i class="fa fa-angle-double-right"></i> Package: {{ trip }}</p>
        <p><i class="fa fa-angle-double-right"></i> Price: {{ price }}$ </p>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-6">
        <span>2</span>
        <h5>Booking Details</h5>
        <p><i class="fa fa-angle-double-right"></i> Credit Card Information</p>
        <p><i class="fa fa-angle-double-right"></i> Billing Details</p>
      </div>
    </div>
    <div class="row detailsrow">
      <div class="col-12 col-sm-12">
        <form method="POST" action="{% url 'booking-form' %}">
            {% csrf_token %}
                <div class="row">
            <div class="col-12 col-sm-12">
              <h4>Booking Details</h4>
            </div>
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Package:</label>
                  <input type="text" name="package" readonly class="form-control" value="{{ trip }}" />
                  
                </div>
              </div>
            </div>
             <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Package Price in USD:</label>
                  <input type="text" name="price" class="form-control" value="{{ price }} USD" readonly>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Trip Start Date(your preference):</label>
                  <input type="date" name="trip_start_date" id="txtDate" class="form-control" required="required">
                </div>
              </div>
              
            </div>
            
            <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Full Name:</label>
                  <input type="text" name="full_name" class="form-control" placeholder="Full Name" required="required">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-md-6 col-lg-6 col-sm-12 form-group">
                <div class="input-group">
                  <label>Email:</label>
                  <input type="email" name="email" class="form-control" placeholder="Email" required="required">
                </div>
              </div>
              <div class="col-12 col-md-6 col-lg-6 col-sm-12 form-group">
                <div class="input-group">
                  <label>Nationality:</label>
                  <input type="text" name="nationality" class="form-control" placeholder="Country" required="required">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-md-6 col-lg-6 col-sm-12 form-group">
                <div class="input-group">
                  <label>Personal Contact No:</label>
                  <input type="text" name="contact_number" class="form-control" placeholder="Contact Number" required="required">
                </div>
              </div>
              <div class="col-12 col-md-6 col-lg-6 col-sm-12 form-group">
                <div class="input-group">
                  <label>Emergency Contact No:</label>
                  <input type="text" name="emergency_contact_number" class="form-control" placeholder="Emergency Contact Number" required="required">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-md-6 col-lg-6 col-sm-12 form-group">
                <div class="input-group">
                  <label>Passport No:</label>
                  <input type="text" name="passport_no" class="form-control" placeholder="Passport number" required="required">
                </div>
              </div>
              <div class="col-12 col-md-6 col-lg-6 col-sm-12 form-group">
                <div class="input-group">
                  <label>Place of Issue:</label>
                  <input type="text" name="place_of_issue" class="form-control" placeholder="Place of issue" required="required">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-md-6 col-lg-6 col-sm-12 form-group">
                <div class="input-group">
                  <label>Date of Issue:</label>
                  <input type="date" name="date_of_issue" class="form-control" required="required">
                </div>
              </div>
              <div class="col-12 col-md-6 col-lg-6 col-sm-12 form-group">
                <div class="input-group">
                  <label>Date of Expiry:</label>
                  <input type="date" name="date_of_expiry" class="form-control"  required="required">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Date Of Birth:</label>
                  <input type="date" name="date_of_birth" class="form-control" placeholder="Full Name" required="required">
                </div>
              </div>
            </div>
            <div class="row">
              
            </div>
            
            <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>No of People:</label>
                  <select name="no_of_people">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                  </select>
                </div>
              </div>
            </div>
           
            {% comment %} <div class="row payment-radio">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Payment options:</label>
                  <input type="radio" id="male" name="gender" value="male">
                  <label for="male">Pay 20% now</label><br>
                  <input type="radio" id="female" name="gender" value="female">
                  <label for="female">Pay 100% now</label>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Total Cost in USD:</label>
                  <input type="text" class="form-control" placeholder="0.00" required="required">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Total Deposit Amount in USD:</label>
                  <input type="text" class="form-control" placeholder="0.00" required="required">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>3.5% Credit Card Processing Fee:</label>
                  <input type="text" class="form-control" placeholder="0.00" required="required">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-12 col-sm-12 form-group">
                <div class="input-group">
                  <label>Total:</label>
                  <input type="text" class="form-control" placeholder="0.00" required="required">
                </div>
              </div>
            </div> {% endcomment %}
            {% comment %} <div class="row">
              <div class="col-12 col-sm-12">
                <img src="{% static 'images/online-pay.png' %}" alt="">
              </div>
            </div> {% endcomment %}
            <div class="row">
            <div class="form-group">
              <div class="col-12 col-sm-12">
                <button type="submit" class="btn btn-primary">Submit <span class="fa fa-paper-plane"></span></button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/booking-success.html
{% extends "base.html" %}

{% block content %}

<div class="page-banner">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12">
                    
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner-bredcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        <ul class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li>Booking Success</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="offline-body">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        <p>Your trip booking for {{ package }} is successfully sent!</p>
        
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/contact.html
{% extends 'base.html'%}

{% block content %}
<div class="page-banner">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner-bredcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        <h1>Contact Us</h1>
        <ul class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li>Contact Us</li>
          {% for message in messages %}
          <div
            class="alert alert-success alert-dismissible fade show"
            role="alert"
          >
            <strong>Message: </strong> {{message}}
            <button
              type="button"
              class="close"
              data-dismiss="alert"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="contact-body">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12 col-md-8 col-lg-8">
        <div class="contact-left">
          <h2>{{ company_info.footer_text_copyright }}</h2>
          <p><strong>Address:</strong></p>
          <p>{{ company_info.address }}</p>
          <br />
          <p><strong>Tel:</strong></p>
          <p>{{ company_info.phone }}</p>
          <br />
          <p><strong>Email:</strong></p>
          <p>{{ company_info.email }}</p>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-4 col-lg-4">
        <form method="post">
        {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <div class="md-form">
                <input type="text" name="name" class="form-control" placeholder="Full name">
              </div>
              <div class="md-form">
                <input type="email" name="email" class="form-control" placeholder="Email Address">
              </div>
              <div class="md-form">
                <input name="phone" type="text" class="form-control" placeholder="Phone(10 digits)">
              </div>
              
            </div>
            <div class="col-md-12">
              <div class="md-form">
                <textarea type="text" name="message" placeholder="Your message"></textarea>
                <button type="submit" class="btn btn-primary">Send Message</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="maps">
  <iframe src="{{ company_info.location_map }}" width="100%" height="500" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>
{% endblock content %}

templates/our-story.html
{% extends "base.html" %}

{% block content %}
<div class="page-banner">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner-bredcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        <h1>Awards And Recognitions</h1>
        <ul class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li>Awards And Recognitions</li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="award-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-12 col-sm-12 col-md-12 col-lg-12">
        <h4>{{ ourstory.heading }}</h4>
        <p>{{ ourstory.description | safe }}</p>
      </div>
      {% for i in ourstory.awardimages_set.all %}
      <div class="col-12 col-sm-12 col-md-4 col-lg-3">
        <a href="#"><img src="{{ i.image.url }}" alt=""></a>
        <h5 class="mt-3">{{ i.title}}</h5>
      </div>
      {% endfor %}
      
    </div>
    
  </div>
</div>
{% endblock content %}

templates/why-us.html
{% extends "base.html" %}

{% block content %}
<div class="page-banner">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-12">
          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="banner-bredcrumb">
  <div class="container">
    <div class="row">
      <div class="col-12 col-sm-12">
        <h1>Why Us</h1>
        <ul class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li>Why Us</li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="why-body">
  <div class="container">
    <div class="row">
    {% for i in whyus %}
      <div class="col-12 col-sm-12 col-md-6 col-lg-4">
        <div class="why-box">
          <i class="fas fa-hiking"></i>
          <h4>{{ i.heading }}</h4>
          <p>{{i.description | safe }}</p>
        </div>
      </div>
      {% endfor %}
      
    </div>
  </div>
</div>
{% endblock content %}